---
title: "FinalProjMD"
author: "Emily Nelson"
date: "`r Sys.Date()`"
output: html_document
---


##Intro & Setup

```{r}

library(shiny)
library(bslib)

```



##UI

```{r}


ui <- navbarPage(
  title = "Dashboard",
  theme = bs_theme(bootswatch = "flatly"), 
  
  #overview page
  tabPanel(
    "Overview",
    fluidPage(
      h2("planning to have overview of project here"), 
      br()
    )
  ),
  
  #dataset 1
  tabPanel(
    "Dataset 1",
    sidebarLayout(
      sidebarPanel(
        h3("Sidebar"),
        p("planning to have dataset description and user inputs here"),
        width = 3
      ),
      mainPanel(
        tabsetPanel(
          tabPanel("Tab 1", h4("Tab 1 content here")),
          tabPanel("Tab 2", h4("Tab 2 content here")),
          tabPanel("Tab 3", h4("Tab 3 content here")),
          tabPanel("Tab 4", h4("Tab 4 content here"))
        ),
        width = 9
      )
    )
  ),
  
  #dataset 2
  tabPanel(
    "Dataset 2",
    sidebarLayout(
      sidebarPanel(
        h3("Sidebar"),
        p("planning to have dataset description and user inputs here"), 
        width = 3
      ),
      mainPanel(
        tabsetPanel(
          tabPanel("Tab 1", h4("Tab 1 content here")),
          tabPanel("Tab 2", h4("Tab 2 content here")),
          tabPanel("Tab 3", h4("Tab 3 content here")),
          tabPanel("Tab 4", h4("Tab 4 content here"))
        ),
        width = 9
      )
    )
  ),
  
  #dataset 3
  tabPanel(
    "Dataset 3",
    sidebarLayout(
      sidebarPanel(
        h3("Sidebar"),
        p("planning to have dataset description and user inputs here"), 
        width = 3
      ),
      mainPanel(
        tabsetPanel(
          tabPanel("Tab 1", h4("Tab 1 content here")),
          tabPanel("Tab 2", h4("Tab 2 content here")),
          tabPanel("Tab 3", h4("Tab 3 content here")),
          tabPanel("Tab 4", h4("Tab 4 content here"))
        ),
        width = 9
      )
    )
  )
)

```



##Server

```{r}

server <- function(input, output, session) {}

```



##Run the App

```{r}

shinyApp(ui, server)

```